/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.server.Server;

public class App {
    public static void main(String[] args) {
        Server.start(6666);
    }
}
