/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public final class App {
    public static void main(String[] args) {
        org.example.Chat.main(args);
    }
}
